### ISSUE TITLE
Undeclared global variable "dreambuilder_theme" at init.lua:1

### ISSUE THREAD

**Issue by wsor4035** [mt-mods/dreambuilder_hotbar#1]
Undeclared global variable "dreambuilder_theme" at init.lua:1
2021-07-15 17:50:51: WARNING[Main]: Undeclared global variable "dreambuilder_theme" accessed at ...minetest-backup/bin/../mods/dreambuilder_hotbar/init.lua:1

**Comment by wsor4035** [comment]
Vanessa Dannenberg @VanessaE · 4 months ago
Maintainer
This is not a critical error, you can safely ignore it. I just didn't bother to use the global-exists API call.

**Comment by S-S-X** [comment]
In my opinion whole global_exists should not even exist and engine should stop playing luacheck...

**Comment by BuckarooBanzay** [comment]
a workaround would be to check `_G.dreambuilder_theme` instead (not sure if the engine complains then)

**Comment by S-S-X** [comment]
> a workaround would be to check `_G.dreambuilder_theme` instead (not sure if the engine complains then)

It will complain, you need to `rawget(_G, "dreambuilder_theme")` to get around that.
Basically core engine just overrides `__index` for mod Lua environment to execute additional checks for every global variable access.

You can also create mod to `setmetatable(_G, nil)` to remove this engine hack and make everything tiny bit faster for global access. (unless engine also protects against doing that, never tried)
