### ISSUE TITLE
Only 9 slots working on Android

### ISSUE THREAD

**Issue by depascalis** [mt-mods/dreambuilder_hotbar#3]
When pressing on a slot above 9 it is not selected. Let me know how I can provide more info if you need it.

Minetest 5.4.2

_btw, the issue link on minetest.net points to gitlab_

**Comment by OgelGames** [comment]
This is an engine bug, I've opened an issue for it: https://github.com/minetest/minetest/issues/13691

I've also fixed the ContentDB link.
