### ISSUE TITLE
use player meta instead of global save file

### ISSUE THREAD

**Issue by Niklp09** [mt-mods/dreambuilder_hotbar#5]
needs a compatibility layer, because player meta can only be edit for online players. (maybe mod storage?)

**Comment by SwissalpS** [comment]
If data needs to be changed when player isn't online, mod storage seems to be the way to go when moving away from file-storage.

When a mod is not likely to need to change stored data while players are offline, using player meta is easier to manage for situations where players are deleted for example.

But if you want to, for example, build statistics about usage, you'll want to use mod-storage.

**Comment by wsor4035** [comment]
could just use player meta, and your compatibility layer is a simple check when players join. wouldnt be a migrate all at once solution however

**Comment by SwissalpS** [comment]
There is also the double transition possible: migrate file to mod-storage on next boot and then gradually move to player meta as they join. But I don't know why a server would want to hurry away from file based storage that much.

Only if minetest were to be dropping file access in future releases would such a step become necessary.
