### ISSUE TITLE
Hotbar sizes wider than the game window don't display correctly

### ISSUE THREAD

**Issue by Bituvo** [mt-mods/dreambuilder_hotbar#9]
My Minetest window is sized in such a way that 24 hotbar slots take up the full width. However, if I set my hotbar to have one additional slot, this happens:

![image](https://github.com/user-attachments/assets/cb4e228a-cd5c-403c-9bc4-58ea17637a12)

**Comment by OgelGames** [comment]
This is an engine issue: https://github.com/minetest/minetest/issues/9269
